export const EXPORT_TABLE_META = {
  ods_inventory_dealer_upn: {
    displayName: "库存基础表",
    fields: ["dealerlpcode", "dealerlpname", "upn", "qty", "year", "month"],
  },
  ods_t2_purchase_monthly: {
    displayName: "T2采购历史表",
    fields: ["parentdealerlpcode", "parentdealerlpname", "sc_bu", "upn", "pl5_code", "pl5_name", "qty", "year", "month"],
  },
  ods_dioh_dealer_upn: {
    displayName: "DIOH规则表",
    fields: ["dealerlpcode", "dealerlpname", "upn", "abc_class", "dioh_days"],
  },
  ods_fcst_lp_pl5_monthly: {
    displayName: "LP-PL5配货预测表",
    fields: ["dealerlpcode", "dealerlpname", "sc_bu", "pl5_code", "pl5_name", "fcst_qty", "year", "month"],
  },
  ods_fcst_t2_pl5_monthly: {
    displayName: "T2-PL5预测表",
    fields: ["parentdealerlpcode", "parentdealerlpname", "sc_bu", "pl5_code", "pl5_name", "fcst_qty", "year", "month"],
  },
  ods_lp_pl5_allocate_monthly: {
    displayName: "LP-PL5配额矩阵",
    fields: ["period_month", "dealerlpcode", "dealerlpname", "pl5_code", "pl5_name", "allocate_qty"],
  },
  ods_upn_active_list: {
    displayName: "UPN范围关系表",
    fields: ["dealerlpcode", "dealerlpname", "pl5_code", "pl5_name", "upn", "year", "month"],
  },
  ods_dealer_upn_dn: {
    displayName: "经销商发货记录",
    fields: ["created_on", "sold_to_pt", "sc_bu", "dealer_type", "material", "delivery_qty"],
  },
  ods_dealer_upn_open_order: {
    displayName: "经销商未清订单",
    fields: ["customer", "sc_bu", "dealer_type", "material", "dctp", "open_qty"],
  },
  ods_bsc_upn_inventory: {
    displayName: "BSC库存",
    fields: ["material", "sloc", "unrestricted_qty"],
  },
  ods_bsc_upn_intransit: {
    displayName: "BSC在途库存",
    fields: ["material", "forecast_date", "intransit_qty"],
  },
  ods_upn_safety_stock_manual: {
    displayName: "安全库存",
    fields: ["upn", "safety_stock_qty"],
  },
  ods_lp_upn_purchase_price: {
    displayName: "Dealer UPN单价",
    fields: ["dealer_code", "dealer_type", "upn", "bsc_std_sell_price", "bsc_std_sell_price_vat", "currency_code"],
  },
  ods_upn_constraint_manual: {
    displayName: "UPN周月约束规则",
    fields: ["period_month", "sc_bu", "upn", "constraint_type", "source_system"],
  },
  ods_upn_bundle_manual: {
    displayName: "UPN套包规则",
    fields: ["upn", "bundle_qty", "source_system"],
  },
  ods_calendar_pattern_weekly: {
    displayName: "周历与周配比",
    fields: [
      "sc_bu",
      "period_month",
      "month_start_date",
      "week_start_date",
      "week_end_date",
      "prev_week_pattern_pct",
      "current_week_pattern_pct",
    ],
  },
  ods_weekly_amount_threshold_manual: {
    displayName: "周金额调整阈值",
    fields: [
      "sc_bu",
      "overage_threshold_pct",
      "shortfall_threshold_pct",
      "source_system",
    ],
  },
  ods_bu_pattern_amount_weekly: {
    displayName: "SCBU周/月预算",
    fields: [
      "period_week",
      "period_month",
      "sc_bu",
      "actual_amount",
      "month_target_amount",
      "month_limit_amount",
      "currency_code",
    ],
  },
  list_lp_pl5_status_monthly: {
    displayName: "LP-PL5状态表",
    fields: ["period_month", "sc_bu", "lp_code", "lp_name", "pl5_code", "pl5_name", "has_quota", "has_history", "quota_qty", "history_qty_m6_m1", "status_note", "error_id"],
  },
  list_lp_pl5_upn_status_monthly: {
    displayName: "LP-PL5-UPN状态表",
    fields: ["period_month", "sc_bu", "lp_code", "lp_name", "pl5_code", "pl5_name", "upn", "has_quota", "has_history", "quota_qty", "history_qty_m6_m1", "status_note", "error_id"],
  },
  calc_batch: {
    displayName: "月拆分结果列表",
    fields: ["id", "period_month", "status", "total_upns", "error_upns", "calculated_at", "created_at"],
  },
  calc_weekly_upn_split_batch: {
    displayName: "周拆分结果列表",
    fields: [
      "id",
      "period_month",
      "calendar_date",
      "status",
      "total_rows",
      "total_upns",
      "current_week_pattern_pct",
      "month_le_amount",
      "actual_amount",
      "week_pattern_amount",
      "target_pending_amount",
      "suggested_amount_total",
      "week_pattern_gap_amount",
      "week_pattern_gap_pct",
      "overage_threshold_pct",
      "shortfall_threshold_pct",
      "system_default_final_amount_total",
      "system_default_pattern_gap_amount",
      "final_amount_total",
      "final_pattern_gap_amount",
      "calculation_currency",
      "usd_to_cny_rate",
      "calculated_at",
      "created_at",
    ],
  },
  calc_weekly_upn_split_result: {
    displayName: "周拆分结果明细",
    fields: [
      "batch_id",
      "sc_bu",
      "calculation_currency",
      "usd_to_cny_rate",
      "overage_threshold_pct",
      "shortfall_threshold_pct",
      "system_default_final_amount_total",
      "system_default_pattern_gap_amount",
      "final_amount_total",
      "final_pattern_gap_amount",
      "lp_code",
      "lp_name",
      "pl5_code",
      "pl5_name",
      "upn",
      "month_quota_qty",
      "current_week_pattern_pct",
      "aa_month_delivered_suggestion_pct",
      "ab_current_inventory_days",
      "bb_upn_abc_class",
      "be_original_target_inventory_qty",
      "bf_current_inventory_qty",
      "bj_t2_purchase_3m_avg_qty",
      "cc_prev_week_pattern_pct",
      "g_week_quota_pattern_total_qty",
      "month_delivered_qty",
      "n_other_dealer_month_delivered_qty",
      "o_month_delivered_total_qty",
      "open_order_or_qty",
      "other_dealer_open_order_or_qty",
      "s_open_order_or_total_qty",
      "t_open_order_non_or_qty",
      "v_other_dealer_open_order_non_or_qty",
      "w_open_order_non_or_total_qty",
      "x_open_order_total_qty",
      "bsc_inventory_qty",
      "intransit_qty",
      "safety_stock_qty",
      "bsc_available_qty",
      "week_quota_pattern_qty",
      "week_target_pending_qty",
      "week_target_pending_total_qty",
      "inventory_status",
      "suggest_qty",
      "remaining_bsc_available_qty",
      "target_inventory_adjustable_qty",
      "post_suggest_dioh",
      "unit_price",
      "suggest_amount",
      "system_adjusted_suggest_qty",
      "upn_month_cap_qty",
      "constraint_types",
      "adjustment_allowed_flag",
      "monthly_remaining_adjustable_qty",
      "bundle_qty",
      "gap_fill_qty",
      "post_gap_fill_qty",
      "system_default_final_qty",
      "manual_final_qty",
      "final_qty",
      "final_amount",
    ],
  },
  calc_upn_split_result: {
    displayName: "月拆分结果明细",
    fields: [
      "batch_id",
      "sc_bu",
      "dealerlpcode",
      "pl5_code",
      "upn",
      "lp_code",
      "e_t2_mix_portion",
      "f_t2_purchase_3m_avg",
      "g_t2_purchase_m0",
      "h_t2_purchase_mtd",
      "i_t2_purchase_mtg",
      "j_opening_inventory",
      "k_target_days",
      "l_tolerance",
      "q_actual_theoretical",
      "q_star_pl5_theoretical",
      "w_mtg_allocate_qty",
      "r_base_replenish",
      "s_tolerance_replenish",
      "t_adjusted_dioh",
      "current_dioh",
      "replenish_gap_to_30_qty",
      "is_error",
      "error_message",
      "error_id",
    ],
  },
  calc_upn_split_trace: {
    displayName: "月拆分过程追踪",
    fields: [
      "batch_id",
      "period_month",
      "sc_bu",
      "dealerlpcode",
      "pl5_code",
      "upn",
      "lp_code",
      "h_t2_purchase_mtd",
      "e_t2_mix_portion",
      "t_pl5_purchase_m2",
      "u_pl5_purchase_m1",
      "v_pl5_purchase_m0_fcst",
      "f_t2_purchase_3m_avg",
      "g_t2_purchase_m0",
      "j_opening_inventory",
      "k_target_days",
      "l_tolerance",
      "i_t2_purchase_mtg",
      "current_dioh",
      "replenish_gap_to_30_qty",
      "w_mtg_allocate_qty",
      "j_star_pl5_inventory",
      "i_star_pl5_mtg",
      "x_after_allocate_days",
      "m_original_target_inventory",
      "n_new_target_inventory",
      "o_final_target_inventory",
      "p_theoretical_replenish",
      "q_actual_theoretical",
      "q_star_pl5_theoretical",
      "r_base_replenish",
      "s_tolerance_replenish",
      "t_adjusted_dioh",
      "is_error",
      "error_message",
      "error_id",
    ],
  },
} as const;

export const EXPORT_TABLE_FIELDS = Object.fromEntries(
  Object.entries(EXPORT_TABLE_META).map(([key, meta]) => [key, meta.fields]),
) as {
  [K in keyof typeof EXPORT_TABLE_META]: (typeof EXPORT_TABLE_META)[K]["fields"];
};

export type ExportTableName = keyof typeof EXPORT_TABLE_META;

export const VALID_EXPORT_TABLES = Object.keys(EXPORT_TABLE_META) as ExportTableName[];

export function getExportTableDisplayName(table: ExportTableName) {
  return EXPORT_TABLE_META[table].displayName;
}
